# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-07 14:36
from __future__ import unicode_literals

from django.db import migrations, utils, transaction

def forwards(apps, schema_editor):
    print("trying to migrate")
    email_address = apps.get_model('account', 'EmailAddress')
    for user in apps.get_model('auth', 'User').objects.all().order_by("-last_login"):
        if not user.email or not len(user.email):
            print("Error: user %s has no email" % user.username)
            continue

        try:
            with transaction.atomic():
                email_address.objects.create(user=user, email=user.email, verified=user.is_active, primary=True)
        except utils.IntegrityError as e:
            print("%s: failed to create email %s %s verified %s" % (e, user.username, user.email, user.is_active))


def backwards(apps, schema_editor):
    email_address = apps.get_model('account', 'EmailAddress')
    email_address.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_organisation_logo'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
