# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 21:18
from __future__ import unicode_literals

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_auto_20200127_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.IntegerField(choices=[(0, b'Pending'), (1, b'Active'), (2, b'Finished'), (3, b'Archived')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=competition.models.current_year),
        ),
    ]
